### ISSUE TITLE
automatic closing of the window

### ISSUE THREAD

**Issue by lisu26** [DarkLord76865/Autofish-Fishing-Planet#2]
hey, I have a question, will the automatic closing of the window after catching a fish be implemented

**Comment by DarkLord76865** [comment]
Hi,
it is already be implemented. It just might not work always. The thing is that they often change font of in-game letters which messes up with optical recognition which the bot is performing. I just fixed a single bug I have encountered when pop-up window wouldn't close after level-up. If it was the same problem for you, just download new binary and use it, if you encountered some other bug, please screenshot game screen when the bug occured and send here so that I can fix it.
Regards

**Comment by DarkLord76865** [comment]
Since you didn't respond with any additional info on your problem, I will consider this fixed. If you encounter any new bug, open a new issue.
