### ISSUE TITLE
Doesn't pick up fish

### ISSUE THREAD

**Issue by Arhitoque** [DarkLord76865/Autofish-Fishing-Planet#3]
Hello, I would like to ask you to fix the automatic raising or releasing of fish when you have free time and opportunity, we will be very grateful to you and my friends.

**Comment by DarkLord76865** [comment]
Hi,
sure, I will be happy to help. What exactly is the problem? I just tested it and bot clicks on keep after reeling in fish. Do you want it to click on release? Why? If it doesn't click on keep for you, you may be using another language (english is needed so that the button literally says keep), or you may be using screen resolution different that 1920x1080 (it is the only supported screen resolution because I don't have access to other screens to make needed screenshots). If it's neither of those things, would you be kind enough to send me a screenshot of a situation where the bot fails?
Regards

**Comment by Arhitoque** [comment]
Oh, I'm sorry, I didn't know that I needed to put English in the game, because I live on another continent and country, thank you very much for the quick feedback.

**Comment by DarkLord76865** [comment]
Yes, unfortunately English needs to be used. Bot works by literally having a set of screenshots and then comparing what it sees on screen to those screenshots. I have made screenshots in English version of the game, so bot doesn't have screenshots to compare to when another language is used. You'll have to stick to English version for bot to work. Sorry for the inconvenience.
Regards
