### ISSUE TITLE
Bot not skip 

### ISSUE THREAD

**Issue by Dascx31** [DarkLord76865/Autofish-Fishing-Planet#4]
the robot does not pass the window when it catches a fish could and I have them coordinate the position to integrate it into the script thank you everything works if not
Have a good evening

**Comment by DarkLord76865** [comment]
Hi,
can you better describe the issue? What window does the bot not close? Could you provide a screenshot of the window? Note that you need to use the english language in-game for bot to work. I have just fixed an issue I myself encountered so maybe it was the same issue for you so try the new release.
How do you want to integrate the coordinates into the script? I can think of several use cases (like casting to specific coordinates, keeping the same orientation, rowing the boat to the same coordinates every time, ...), but I don't think I can make any of these work. Since bot works by visually analysing what is visible on the screen, it would be hard to do any work with coordinates. It may be possible to acquire some coordinates by reading the game's memory, but I have never done anything similar to that.

Regards 😉

**Comment by DarkLord76865** [comment]
I'm glad I could help solve your issue. Unfortunately float fishing probably won't be added any time soon. Keep an eye on releases though to see if it gets released.
