### ISSUE TITLE
Keeping fish

### ISSUE THREAD

**Issue by Stizzie** [DarkLord76865/Autofish-Fishing-Planet#6]
Happened to come across this and I want to say nice work. I've worked on something similar myself.
I don't know what I've set up wrong but the program is not keeping the fish and reinitiate another cast, it just stucks on the fish examination screen.

**Comment by Stizzie** [comment]
AH, turns out AMD Image Shapening was the cause.

**Comment by DarkLord76865** [comment]
Glad you managed to solve the issue. I never thought that AMD Image Sharpening could cause something like this, but it is understandable as it modifies the image on the screen and the bot is using pre-saved image templates for matching on to what is currently visible on the screen.

Regards 😃

**Comment by Stizzie** [comment]
It's crazy how similar my approach is to yours. My script is written in Autohotkey language and also based on image search to send corresponded inputs. I was smiling looking through your code and saw names like "hook,bite,reelin" for different states. I used exactly those name haha !

Anyhow while you at it can you elaborate on the auto time warp funtion ?

**Comment by DarkLord76865** [comment]
I'm glad to hear that 😄.
Don't bother much with that time warp function. That part of the bot is very much unfinished. As of right now that function gets called only if the full keepnet gets detected. Then, if auto time warp was turned on, it presses "t" to open time warp window and searches for the next morning button. If it can't find the next morning button, it waits for 3 seconds and tries again forever until that button is found (that is because if you time warp during the day, there is a cooldown for another time warp, so this function might get called before that cooldown has expired, so it basically just waits for the cooldown to end, then it detects next morning button and continues.). Obviously this kind of time warp isn't very good, what if a person wants to only fish at night for example? Also wouldn't it be better to fish only during peak times? All this stuff seemed too hard to solve so I never did, and I kinda doubt I ever will... 😢 Some of those problems include: how do you detect peak times?, if you detect how to decide to when to warp so that you don't have to wait for warp cooldown?, how do you select exact time to warp to? (this could probably be solved by including templates of all hours displayed, but that is a lot of work), what about night fishing, there is no cooldown at night, which time do you choose then?
As you can see, it isn't easy at all to do this so it will just remain as is for now.
Happy to hear I'm not the only one doing the bot for Fishing Planet 😄.
Good luck developing yours. 😃

**Comment by DarkLord76865** [comment]
P.S. I feel sorry for you reading such a bad organised code as this one. I would do it much much better if I was doing it again now. :smiley:
